### ISSUE TITLE
[Need assistance]

### ISSUE THREAD

**Issue by vikaskyadav** [Data4Democracy/immigration-connect#1]
Help needed on how to contribute to this repo.

**Comment by jtorrez** [comment]
Hey @vikaskyadav , we'll have more action items as soon as we speak with the NILC about what they need help with the most. Thanks for wanting to contribute!

**Comment by jtorrez** [comment]
@vikaskyadav I've added some issues for this project that you can check out and get involved with. Thanks for posting here!
