### ISSUE TITLE
Analyze and organize tweets and statements regarding Muslim ban

### ISSUE THREAD

**Issue by jtorrez** [Data4Democracy/immigration-connect#12]
@alejandrox1 has collected a huge amount of tweets and other sources regarding the Muslim travel ban and compiled them [here](https://github.com/Data4Democracy/immigration-connect/tree/master/travel-ban/tweets). We need to analyze and organize them for deliver to the NILC. An example of how we delivered data to them in the past can be found on [their website](https://www.nilc.org/issues/litigation/trump-tweets-with-muslim-muslims/).

Please also see the exploratory notebook that @alejandrox1 has put together [here](https://github.com/Data4Democracy/immigration-connect/blob/master/travel-ban/search_tweets.ipynb) for more ideas and feel free to perform any other analyses you think may be of interest to the NILC and their partners.

**Comment by dpaolella** [comment]
@jtorrez Are there any specific questions that the NILC would like to see answered from this analysis? Or is the task more to better filter the tweets by relevance and/or some measure of significance? It looks like some of the tweets that were collected aren't actually related to the ban.

**Comment by meriburgess** [comment]
If no one else has started this, I wouldn't mind giving it a go!
