### ISSUE TITLE
Perform analysis that allows us to tell stories related to DHS/ICE expenditures

### ISSUE THREAD

**Issue by jtorrez** [Data4Democracy/immigration-connect#19]
Here are a few example stories we are interested in:

* The US taxpayer pays X amount of taxes per year, it costs Y amount of dollars to deport someone.
* What else could we use all the money being spent on deportation instead?
* Any other interesting stories that are related to DHS/ICE, be creative!

**Comment by AlexPapas** [comment]
Is there any dataset available. Excuse me but I am completely new on this and I try to figure out how this works.

Kr,}
Alex

**Comment by jtorrez** [comment]
@AlexPapas sorry for the late reply, it has been a busy past few weeks for me at my job.

There isn't any datasets available for this analysis; part of the fun (in the data nerd sense) is that you'll get to build the analysis from the ground up. That being said, we have collected a few potential data sets and relevant articles for background research on our data.world page: https://data.world/sjhaveri/how-effectively-does-the-dhs-ice-use-the-funds-they-already

Check it out and feel free to assign yourself this issue if you're interested in taking this on!

**Comment by jtorrez** [comment]
Closing to clean up outdated issues
