### ISSUE TITLE
Discuss best mobile app for secure internal communications within the NILC

### ISSUE THREAD

**Issue by jtorrez** [Data4Democracy/immigration-connect#2]
The NILC would like suggestions for the best app to use for internal communications. The requirements are simple, quotes directly from the NILC:

- "a mobile app that would not require us to be sitting at our computers

- "Slack came to mind, but some thought that maybe we need something more secure."

I'm thinking Signal or WhatsApp would most likely solve this problem, but would love to hear any other suggestions.

**Comment by 243** [comment]
I'll plug Wire. Open Source, multi-platform, and prettier than the other options.

**Comment by jtorrez** [comment]
Hadn't heard of Wire, but wow that looks dope!

**Comment by jtorrez** [comment]
@243 Thanks for the suggestion, we had a meeting with the NILC yesterday and they liked the look of Wire, looks like they'll probably go with that.
