### ISSUE TITLE
Scrape Social Media for Requested Data

### ISSUE THREAD

**Issue by jtorrez** [Data4Democracy/immigration-connect#20]
# NILC Requests

The following is the data that has been requested by the NILC. The list has simply been reproduced directly from their proposal, feel free to modify it (other than the required data) by removing or supplementing it in whatever ways you believe would allow you answer the research question (see [Milestone](https://github.com/Data4Democracy/immigration-connect/milestone/4) for more details). For example, the NILC only requested Twitter data, but you may want to explore other social media sources.

It is highly suggested you take advantage of the infrastructure and tools that the D4D community has already built to scrape social media data. [Quorum](https://github.com/Data4Democracy/quorum) is a great place to start, see @alejandrox1 for assistance.

## Time Period

January 1st, 2014 to present.

## Required Data

Tweets that contain the following hashtags:
* #Health4All
* #HealthforAll

## Stretch Goal

Tweets that contain the following keywords or hashtags or mentions:
* Health
* Insurance
* Coverage
* Illegals
* Undocumented
* All
* Immigrant
* Immigrants
* Lara
* Kids
* Children
* #Health4Kids
* #HealthforKids
* Mentions of @senricardolara

**Comment by jtorrez** [comment]
[Data for Democracy Project Proposal - Jackie Vimo.docx](https://github.com/Data4Democracy/immigration-connect/files/1203265/Data.for.Democracy.Project.Proposal.-.Jackie.Vimo.docx)

Original Proposal by the NILC for more context

**Comment by saipranava** [comment]
Hello @jtorrez. I'm interested in taking part in all the stages of the NILC project. I went through the project proposal and get an idea of what is expected. I don't know Python, so found it difficult to follow what was there on the quorum page. So, I used R (and the twitteR package) to do this. I have managed to find 812 tweets using 'Health4All' and 2878 tweets using 'HealthforAll'. I'm just wondering if this is the number of tweets you are expecting or is this small?

**Comment by jtorrez** [comment]
Seems low to me, what were your constraints for the search? Did it go all the way back to Jan 2014? And no worries, use whatever language you are comfortable with

**Comment by saipranava** [comment]
Hmm, after discussing with people who have experience with scraping data from twitter, I have understood that the free API's of twitter have a limitation where users can scrape data only of the last 1 week. If we need more, we have to use their commercial API. Since D4D is a non-commercial organisation, we can request to let us access this data for free. May be the folks who have been at D4D for a long time can take that up.

If there is an alternative that works with R, I'm ready to learn and work on it. If there is an alternative in any other language, would wait for people to work on this and I'll join in the analysis/visualisation steps.

**Comment by jtorrez** [comment]
I would say to ping @alejandrox1 (@alarj in Slack) about this first as he is leading the Quorum project and is our local Twitter scraping expert and may have some ideas to help you get the data. But if he is out of ideas, then we'll just have to punt on this.

**Comment by brucerowan** [comment]
@saipranava  @alejandrox1 any update? I'd like to help with this if it is possible.

**Comment by jtorrez** [comment]
@brucerowan No one has claimed this part the project yet, so if you're interested go for it! Let me know if you have questions (@jtorrez in the D4D slack)

**Comment by saipranava** [comment]
@brucerowan @jtorrez I have been speaking to alejandrox1 for the last couple of days. He says that he knows the tools that have the ability to pull the required data without using any software and I have been learning to use those tools. If you are interested the first thing you have to do is this https://docs.docker.com/get-started/
Complete the tutorial and then if you already know Python do this https://doc.scrapy.org/en/latest/intro/tutorial.html 
If you don't know Python I would strongly recommend doing a good intro course before getting your hands on scrapy.

If you are using windows, let me know before you start with the docker tutorial, the tutorial has a couple of small mistakes and stuff, for which I can give a detailed explanation.

Once we finish these two tutorials we should be good to start scraping the required data.

**Comment by jtorrez** [comment]
@saipranava Since you've already been tackling this I went ahead and assigned this issue to you so people will know to contact you if they want to get involved. 

Definitely can attest both Docker (especially Docker) and Scrapy are super useful tools, we use them all the time at work! 

@brucerowan Please coordinate with @saipranava as to how you can help with the project, I'm sure there are places the two of you can work together.

**Comment by sharonresheff** [comment]
Looks like we've been working on this in tandem as I also downloaded Docker and Scrapy and am trying to learn Scrapy for this project. @saipranava - since I am very new to programming and have no experience with the scraping part I wonder if I can help in this stage? Should I try to do my own scraping or join for the analysis, visualization, and reporting piece where I have experience?

**Comment by saipranava** [comment]
@sharonresheff I'm also pretty new to programming and I'm finding it a bit difficult to spare time to learn Python from scratch and understand scrapy. 

So, I would recommend you to go ahead and learn scrapy. Chances are you'll learn it before me and be ready to grab the data :) 

Even if all 3 of us end up learning scrapy, we have multiple search terms in the project and we can share it among us.

**Comment by sharonresheff** [comment]
Sounds good @saipranava I need more Python deep dive as well in order to get a handle on Scrapy. Let's keep each other in the loop for now.

**Comment by alejandrox1** [comment]
Hi everyone @sharonresheff @saipranava @brucerowan @jtorrez I have some twitter scrapping code sitting [here](https://github.com/alejandrox1/twitter_tools). Also, there I made a Docker image (to avoid all the setup required by Selenium) called [alejandrox1/ubuntu_pyselenium](https://hub.docker.com/r/alejandrox1/ubuntu_pyselenium/)

**Comment by jtorrez** [comment]
@sharonresheff and @saipranava any progress on this? 

@alejandrox1 thanks for your support!

**Comment by saipranava** [comment]
@jtorrez
I have had experienced too many issues while trying to learn scrapy. I don't have the time to learn Python from the scratch at the moment and it doesn't look like the are any methods in R to scrape this kind of data. So, I have not done anything regarding the the scraping part. I'm hoping someone else who is well versed with python and docker can work on this. I'm ready to do the steps after that though.

**Comment by jtorrez** [comment]
No worries, thanks for the update @saipranava

**Comment by sharonresheff** [comment]
I have taken upon myself to learn Python from scratch. No small task. Can't help yet.

**Comment by jtorrez** [comment]
No worries, just checking in @sharonresheff. Appreciate the update

**Comment by brycecf** [comment]
@jtorrez I just started watching this project.  I'm very familiar with writing Twitter crawlers.  Is there still a need? If so, I'd be happy to help!

**Comment by jtorrez** [comment]
Hi @brycecf! Yes, we definitely have a need here. Since they are requesting a historical scrape, this has been a kinda tough one. If you are willing to take it on, it would be much appreciated as the NILC would love to get this done and we have multiple people wanting to help in the parts of this project that come after we have data!

**Comment by brycecf** [comment]
@jtorrez Sure, I'd be happy to help! I probably won't be able to get to this today, but I'll have an update for you by Saturday.

Few questions:
* What format do you want this in?
* How do you want to treat **Required** versus **Stretch**?  Do you want these as separate data sets?
* Could you add me to the Slack channel? I can send you a private message with my email.

**Comment by jtorrez** [comment]
A flat file dump should work fine, either json or csv, whichever you are most comfortable with. Most of our members work in Python (with Pandas) or R, so if you could put it into a format that allows it to be easily loaded into a dataframe type structure, that would be great! (So if JSON, each entry having consistent field names, etc.) You don't need to clean the data much if the format makes it easy to load; lots of experience around here (and if not, it'd be good experience) with doing that.

Hmm, I'm torn on keeping them separate. Keeping them separate may be a good idea to reduce the amount of cleaning since there is a main focus for the analysis, but technically they all belong to the same population.....yeah, maybe just keep them separate and format them in a way that it's easy to put the two data sets together (same column names and such).

And yes! Please send me your email and I'll get you an invite to the Slack

**Comment by brycecf** [comment]
Sorry, the weekend was busier than I expected. I'll be working on this today (Tuesday).

**Comment by brycecf** [comment]
@jtorrez I've collected 22,118 Tweets for #health4all and 42,670 for #healthforall that are dated since 01/01/2014.  I need to edit the formatting a little bit, but I will open a pull request with the data by the end of the day.  Just as an FYI, I do not know if this was intended or not, but these hashtags are being used by other users in contexts that do not relate to immigration, so this data is noisy if NILC is just interested in that usage.

I will work on the stretch goals after uploading this data.  I want to space out my collection so as not to irritate Twitter.

**Comment by saipranava** [comment]
@brycecf Great work man. I was just wondering what tools you used to get this work done and how a beginner can go about making to use them. Did you use scrapy or something else?

**Comment by brycecf** [comment]
@saipranava I used scrapy. I'm going to work on cleaning up my script and posting it as a tool so others can use it to scrape historical Tweets too.

**Comment by jtorrez** [comment]
Awesome, thanks so much @brycecf, this is super helpful. Are you interested in working on the next phase of this (#22)? I know that @saipranava was ready to jump on that if you aren't.

**Comment by saipranava** [comment]
@brycecf Cool, will be looking forward to your tool!

@jtorrez I'm ready to work on this and it looks like quite a few people have shown interest. I'm an amateur at this so its better we we have a few experienced people on this. The more the better I guess. Is there a slack group for the NILC project?

**Comment by brycecf** [comment]
@jtorrez, @saipranava Yes, I'd like to help out with #22 and #23

**Comment by sharonresheff** [comment]
@jtorrez @saipranava @brycecf I'll also take a stab at the analysis part. Maybe we can each tackle it and compare the outcome?

**Comment by jtorrez** [comment]
@sharonresheff I think that is a great idea, @saipranava and @brycecf you in for that? If so, I'll assign the three of you to those other two issues (#22 and #23)

**Comment by saipranava** [comment]
Yup. Sounds good.
