### ISSUE TITLE
Upload Collected Data to data.world or Github

### ISSUE THREAD

**Issue by jtorrez** [Data4Democracy/immigration-connect#21]
After completing #20, upload the data to data.world or Github so that the D4D community can access it. 

Feel free to ping [@jtorrez](https://datafordemocracy.slack.com/messages/@jtorrez/) or [@sanjana.jhaveri](https://datafordemocracy.slack.com/messages/@sanjana.jhaveri/) on Slack if you need assistance using data.world, which is our preferred location for shared data.

**Comment by brycecf** [comment]
@jtorrez I guess I'll be assigned to this too given #20.
