### ISSUE TITLE
NILC DACA Assistance

### ISSUE THREAD

**Issue by jtorrez** [Data4Democracy/immigration-connect#25]
NILC would like help collecting any data, articles, material, etc. related to DACA and the recent decision to rescind it by the Trump Administration. 

This issue is just a temporary dumping ground for any and all ideas and found data/articles/materials related to assisting them. We will re-organize once concrete projects and analyses emerge from the brainstorming.

**Comment by Glaze-S** [comment]
This seems like a good starting point:
https://data.world/caitlyn/states-where-those-affected-by-daca-live

**Comment by Glaze-S** [comment]
**News-related brainstorming, could be useful to see how the narrative is shaping up.** 
_Not immediately useful for day-to-day experiences of people directly affected. But could be useful to community organizers, especially for local news sources. Organizers will want things like: statements from their reps, local news stories (and how they are similar/different than national coverage). Names of key targets (like an elected official) who can be moved to take action by writing, clarifying, or undoing policy._

I used [EventRegistry](http://eventregistry.org/search?type=events&query=%257B%2522conditions%2522:%255B%257B%2522id%2522:1,%2522label%2522:%2522DACA%2522,%2522negate%2522:false%257D%255D,%2522preferredLang%2522:%2522eng%2522%257D&tab=eventClusters&eventsSortBy=socialScore) to make these:

![topconceptsinevents-entities and nonentities](https://user-images.githubusercontent.com/25102590/30237872-59753a38-94f0-11e7-80e4-9d925df6ab23.png)
![events - tag cloud](https://user-images.githubusercontent.com/25102590/30237873-597541fe-94f0-11e7-9634-9d5042b14b96.png)
![events - timeline](https://user-images.githubusercontent.com/25102590/30237875-59760562-94f0-11e7-813b-0f5ec3535cb1.png)
![events - top news sources map](https://user-images.githubusercontent.com/25102590/30237877-5978740a-94f0-11e7-9ae7-cb3ffd26530f.png)
![events - top news sources](https://user-images.githubusercontent.com/25102590/30237874-59760936-94f0-11e7-9979-542262810f10.png)
![events - clusters](https://user-images.githubusercontent.com/25102590/30237876-59775f7a-94f0-11e7-97b9-f1fec082fbc5.png)

The Dendrogram is particulary interesting for generating some brainstorming ideas.

**Services and Immediate Needs-related brainstorming**
_These could be immediately useful to the millions of people affected. It might be hard to make something that does not a) get lost in the proliferation of info about what to do and b) become outdated or delayed (as new information becomes available). The best tools might connect people to trusted sources that update regularly (e.g., directs to NILC for legal or- is less reliant on rapidly changing information. For example, a tool that directs people to existing resources or helps people build capacity might be helpful. Especially if it includes information for those who are hoping to help but are not immediately affected. Another idea would be to put some of this larger contextual data- like from news stories- next to the research on DACA outcomes to highlight incongruities, give people easy talking point ideas, or just to drive data collection that is responsive to these tensions.  _
My networks are trying to get people connected with local resources. Clinics. Legal support. Emergency Preparation. Fundraising to get paperwork and/or legal fees taken care of.

_Direct service provided by fundraising, already. It might be useful to make a tool to help people quickly build capacity. For example a, "Here are things to do to help"._ 
_¿Ocupan fondos para renovar su DACA? ¡Rellenen este formulario! / Need funds for your DACA renewal? Fill out this form!_
https://docs.google.com/forms/d/1UH8vGV2Dp_xZe-0DheNusp93EkkywDaYZl9TQXlXRCw/viewform?edit_requested=true

"one way we can support undocumented families is fundraising for those whose DACA expires on or before March 5 2018 to apply for a 2-year renewal before October 5 of this year. With shipping, it costs $500+ for one youth to renew their DACA."
_Join Fuerza Colectiva in raising funds for DACA applicants! DONATE HERE: youcaring.com/fundDACArenewals_

**There have been several reports on the DACA outcomes**

1. Migration Policy Institute's DACA brief contains labor, education, demographics data for DACA recipients.
[DACA-Occupational-2017-FINAL.pdf](https://github.com/Data4Democracy/immigration-connect/files/1289597/DACA-Occupational-2017-FINAL.pdf)
2. American Progress has a report
[Wong-Et-Al-New-DACA-Survey-2017-Codebook.pdf](https://github.com/Data4Democracy/immigration-connect/files/1289601/Wong-Et-Al-New-DACA-Survey-2017-Codebook.pdf)
 that includes survey data about labor, bilingualism, inclusion, wellbeing, among other outcomes. For more details about the survey, contact Dr. Tom Wong at tomkwong@ucsd.edu. The article outlining the survey is at https://www.americanprogress.org/issues/immigration/news/2017/08/28/437956/daca-recipients-economic-educational-gains-continue-grow/.

**In terms of data collection, to avoid collecting data from such a vulnerable population. I suggest we consider collecting data on a less vulnerable group**
_Professional allies, teachers, lawyers. It would be great to collect data to find out what *they* need to be effective supports for people with DACA, families, and loved ones. Do lawyers need childcare to compensate for the longer hours? Do teachers need lesson plans? Do family liaisons need volunteers to make copies or answer calls? Coffee? Donated Pizza? A dog walker? Art? What are ways that we can help to support people targeted communities? When people can't donate money to support migrants directly, what are ways they can volunteer their time and/or services to help increase the families who are getting the help they need in this difficult time?_

**Comment by biskwikman** [comment]
There are some studies by think tanks about the economic cost of potentials deportations associated with the rescinding of DACA. [This CATO study](https://www.cato.org/blog/economic-fiscal-impact-repealing-daca) places the cost at around $360 billion, while the [Center for American Progress estimates](https://www.americanprogress.org/issues/immigration/news/2017/07/21/436419/new-threat-daca-cost-states-billions-dollars/) the cost at about $400 billion.

CATO is a libertarian think-tank while CAP is more typically left wing.

**Comment by biskwikman** [comment]
[Here is a write-up about a survey from CAP](https://www.americanprogress.org/issues/immigration/news/2017/08/28/437956/daca-recipients-economic-educational-gains-continue-grow/) which shows that DACA allowed the recipients to earn more money and attain higher education levels.

**Comment by biskwikman** [comment]
[A study in The Lancet](http://www.sciencedirect.com/science/article/pii/S2468266717300476) showing that DACA conferred mental health benefits to its recipients.

[A study in Science](http://science.sciencemag.org/content/357/6355/1041)(paywall) which shows that children of mothers who are able to receive DACA have improved mental health.

**Comment by biskwikman** [comment]
[A study from the Journal of Adolescent Health](http://www.sciencedirect.com/science/article/pii/S1054139X17300514) showing that DACA "potentially improves health outcomes" for young asian and pacific-islander youth.

**Comment by jtorrez** [comment]
@biskwikman thanks for all the work! Would you like to compile your work and @Glaze-S's work into some kind of brief/summary that I could deliver the NILC? Perhaps something that summarizes the source and the potential story/conclusion drawn by the source so that the NILC can determine what communication campaigns might be built around the data/reports you've found

**Comment by biskwikman** [comment]
@jtorrez I would be happy to do that. I'll start on it tomorrow (Australian tomorrow). Would this just be a concise written document? With potential outcomes for DACA recipients (or others) based off of what we have found?

**Comment by jtorrez** [comment]
@biskwikman That sounds perfect. If you're willing to, go ahead and write something up and then we can iterate on it if Patrick (@pato1974, who is our NILC contact) feels things need to change or be added.

**Comment by biskwikman** [comment]
@jtorrez I've had a shot at writing the summary of the studies posted above and some others, along with some ideas for narratives that could come from them. The event registry visualizations that @Glaze-S did seem interesting but I'm not sure how to include in this type of document or what conclusions to draw from them. If either of you or anyone else have ideas on how to do so that may be helpful. Otherwise, what I have so far is in this google docs link, I've allowed editing: 

https://docs.google.com/document/d/1Lo5PMhMatFco_yyKq9WQbP8w-dJkk7VKxzBRJ4o_kks/edit?usp=sharing

Keep in mind I'm no lawyer so I just had a guess at what might be most legally relevant in the narratives section.
