### ISSUE TITLE
Document Project Github Repo Workflow

### ISSUE THREAD

**Issue by jtorrez** [Data4Democracy/immigration-connect#33]
Write markdown detailing the Git/Github workflow this project uses.

**Comment by esjewett** [comment]
Generally this would go under `contributing.md` and then you get some nice reminders automatically in the Github UI. https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by jtorrez** [comment]
Awesome, thanks so much @esjewett I didn't know about that feature!
