### ISSUE TITLE
Discuss and develop email parsing system for NILC

### ISSUE THREAD

**Issue by jtorrez** [Data4Democracy/immigration-connect#4]
The NILC has been overwhelmed with contacts from lawyers, congressional contacts, volunteers, and (most importantly) individuals affected by the immigration policies being put in place by the current administration.

They have a large backlog of emails that will have to be manually sorted and it would be a great help to them if we can help automate at least part of the this process. Their current plan is to have our contact at the NILC and an intern comb through them! 

Any ideas on how to develop this system or information we need to know from the NILC to develop such a system would be much appreciated!

**Comment by 243** [comment]
Okay, for the sake of dumb ideas: What if the NILC sent out an autoreply to all recent contacts. Something like, "We have received your email. Please fill out this online form to help us classify your message." 

Or even a low-tech solution like "Please reply with one of the following keywords to help us classify your message..."

**Comment by violaglenn** [comment]
Document clustering could offer at least a first step-- it might highlight some big issue areas and allow for routing to the correct individual for further sorting. I can also be effective in identifying/weeding out any form letters that are coming in from many locations.

**Comment by jtorrez** [comment]
Thanks for the suggestion @violaglenn! This project is on the back burner for a bit while we work on a few other priority projects, but when this gets rolling we'll definitely make use of your suggestion

**Comment by jtorrez** [comment]
Thanks to @alejandrox1 who will be taking the lead on this issue. We will be discussing this system with the NILC at the next meeting with have with them, more details to follow

**Comment by alejandrox1** [comment]
We can build off the email [forwarding](https://github.com/Data4Democracy/immigration-connect/blob/master/NILC_priorities.md) system to process all emails and then build a nice app or something of the sort for people at NILC to use as a "search engine" as they please.

**Comment by jtorrez** [comment]
Closing this as the NILC has asked us to focus on other things.
