### ISSUE TITLE
Research to Support CIRC Bill in Colorado

### ISSUE THREAD

**Issue by jtorrez** [Data4Democracy/immigration-connect#42]
One of the advocates for our partner organization, the National Immigration Law Center (NILC), has requested that D4D help with a research question they need answered in support of a bill their advocacy organization will be introducing in Colorado later this year. Please read the attached project proposal and ask any questions you may have here, or simply comment that you would like to be assigned this task.

This is a research project with an external stakeholder who is invested in the research question and you have the potential to contribute to the passing of a statewide bill! Please tag either myself (@jtorrez) here or in Slack if you would like further information, and you can also tag @pato1974 who is our NILC rep if you'd like to ask him questions directly.

[D4D-NILC Research Proposal - CO.docx](https://github.com/Data4Democracy/immigration-connect/files/1640515/D4D-NILC.Research.Proposal.-.CO.docx)

**Comment by proof-by-accident** [comment]
Hi, I'm new to this project and was interested in taking a swing at this issue (I'm a CO resident so it's especially close to home).  Quick question: the proposal mentions "...data from TRAC  states that 50% of the people arrested by ICE were never convicted of the orignal crime for which they were charged," do you know where this data would be?  The linked webpage hosts a bunch of datasets, but it's not clear to me where the 50% number is coming from.

**Comment by jtorrez** [comment]
@proof-by-accident thanks for your interest! I've forwarded your question on to the advocate who submitted the project proposal to see if we can dig up the answer. 

Would definitely love to have someone get rolling on this project, so if you're willing to take it on that would be great!

**Comment by pato1974** [comment]
Hi. This is Patrick at the National Immigration Law Center – the advocate who submitted the project proposal. However, I am not the lead advocate on the project and would love to connect you and our lead advocate directly so that she can try to answer your question and both of you can discuss how to move forward with the project.  Can you send me an email for you and I can connect the two of you through email. Thanks!

**Comment by jtorrez** [comment]
@proof-by-accident ^ Please see Patrick's above message, his email is in the message or you can DM him in the D4D Slack where his handle is `pato1974`. Feel free to also email me at jonathan.a.torrez@gmail.com  or DM in D4D slack, I'm `jtorrez`, and I can connect the two of you.

**Comment by proof-by-accident** [comment]
Great, thanks!  I'll send a DM on Slack.

**Comment by dotj** [comment]
Closed due to inactivity
