### ISSUE TITLE
Collect Datasets for Black History Month Project

### ISSUE THREAD

**Issue by jtorrez** [Data4Democracy/immigration-connect#43]
D4D and data.world are partnering to tell stories with data for Black History Month! The D4D-Immmigration-Connect partners with the National Immigration Law Center (NILC) and our contact at the NILC has suggested preparing and analyzing datasets related to Black immigrants to the United States. This report can be used as a starting point to find and upload datasets for further analysis or visualization: http://www.stateofblackimmigrants.com/assets/sobi-fullreport-jan22.pdf

I have started a project page on data.world (https://data.world/jtorrez/immigration-connect-black-history-month) where data can be uploaded, and it would be great if we could find and upload some of the datasets contained in the report before the project starts!

Just to clarify:

What would be extra helpful is if, in addition to locating the URLs of the original data sources mentioned in the email, the data from those sources is downloaded, cleaned (just to get it in the correct format, e.g. a csv for tabular data), and uploaded to data.world so that others can start analysis or visualization with minimal effort.

**Comment by jhzsquared** [comment]
@jtorrez I would love to help out with this project. However, just to check about time, is there a deadline? (I'm new to D4D)

**Comment by jtorrez** [comment]
Hi @jhzsquared! Welcome to D4D! The sooner the better on this one so that you (or others) can get a chance to do some analysis/visualizations before Black History Month (February) is over. Going through the report that is linked and trying to find some of the datasets they use is definitely the best way to get started on this. Let me know if you need any help!

**Comment by jtorrez** [comment]
@jhzsquared Has uploaded many files to the data.world project, thanks so much for that hard work!

The files could probably use some cleaning up to put them in a format that is easily loadable for data analysis (w/ Python, R, etc.); currently they are formatted in Excel XLS files that are made more for humans than our computers. If anyone wants to tackle that, it would be very helpful for others who want to do viz or analysis and don't have enough time to clean things!

**Comment by keshavramaswamy** [comment]
Hi @jtorrez - I can get started - try cleaning the files, aggregating etc. and make it easier for data analysis! But since, it's March now, is this issue and #44 high priority now?

**Comment by jtorrez** [comment]
@keshavramaswamy Even thought Black History Month has passed, our partner organizations would definitely still benefit from any work that could be done, so please do get started on anything you have time for! And let me know if you have any questions I can answer.

**Comment by jtorrez** [comment]
Accidental closing of issue, oops
