### ISSUE TITLE
Start the Public Charge Project 

### ISSUE THREAD

**Issue by dotj** [Data4Democracy/immigration-connect#48]
The National Immigration Law Center (NILC) would like help collecting and storing data from a regulation.gov page for a proposed “Public Charge” rule which targets immigrants who may depend on government benefits.

We want to collect
1) Primary Documents;
2) Supporting Documents; and
3) Comments
and automatically store them in a database.

The regulation.gov page is:
[https://www.regulations.gov/docket?D=USCIS-2010-0012](https://www.regulations.gov/docket?D=USCIS-2010-0012)

Current Timeline:
- The comment period closes on **December 10**.
- This proposal is being presented on **October 23**.
- **Goal:** to have the database capturing data by the **first week in November**.

Skills needed include:
- Data/web scraping
- Database setup

Full proposal from the NILC: [https://docs.google.com/document/d/1PGrztVYkdlTfuXADx9kI0vQciXf3fRpJrgTlV76DPTI/edit?usp=sharing](https://docs.google.com/document/d/1PGrztVYkdlTfuXADx9kI0vQciXf3fRpJrgTlV76DPTI/edit?usp=sharing)

**Comment by alejandrox1** [comment]
Hi, world. I started doing some work related to this issue https://github.com/alejandrox1/scrapers/tree/master/regulationgov

**Comment by dotj** [comment]
Thanks @alejandrox1 ! Like I mentioned on slack - go ahead and submit a PR with your script and we can start reviewing. :)

I can create subsequent issues for the remaining tasks as well.
