### ISSUE TITLE
Build interactive visualization for NILC website

### ISSUE THREAD

**Issue by jtorrez** [Data4Democracy/immigration-connect#5]
Build an interactive map that:
 1. Shows the location of incidents on a interactive map.
 2. Shows number of people impacted at that incident
 3. Map is updated when new data is added
 4. Maps also displays some basic numbers:
    - total number of incidents
    - incidents in last 24 hours
    - etc.

The map could be embedded on a page on their website http://www.nilc.org .  Or it could be a separate lightweight single-purpose website running on a subdomain such as http://incidents.nilc.org

**Comment by jtorrez** [comment]
Sample (fake) data for dev purposes had been uploaded, find it [here](https://github.com/Data4Democracy/immigration-connect/tree/master/data/nilc-int-visualization)

**Comment by pratheekrebala** [comment]
Hey @jtorrez - do you still need help with this?

**Comment by jtorrez** [comment]
Hey @pratheekrebala thanks for the interest but @tylerjrichards and @scottcame are working on this, sorry we didn't keep the issues up-to-date, this has been moving crazy fast. If you're interested in getting involved DM them on Slack or jump into the [#immigration-connect](https://datafordemocracy.slack.com/messages/immigration-connect/) channel.

**Comment by QuinnLee** [comment]
@jtorrez the link to the fake data is broken, is there an updated link I can tinker with?

**Comment by jtorrez** [comment]
Hey @QuinnLee, thanks for the interest!

Get in contact with @scottcame if you are interested in working on on the project or jump into the [#immigration-connect](https://datafordemocracy.slack.com/messages/immigration-connect/) channel to check out the latest developments, as this is pretty far along at this point

**Comment by jtorrez** [comment]
Visualization has been built and we are waiting on the NILC to decide how to utilize the tool
