### ISSUE TITLE
Create database for the Public Charge Project

### ISSUE THREAD

**Issue by dotj** [Data4Democracy/immigration-connect#54]
Context:
- [NILC Proposal](https://docs.google.com/document/d/1PGrztVYkdlTfuXADx9kI0vQciXf3fRpJrgTlV76DPTI/edit?usp=sharing)
- [regulation.gov page](https://www.regulations.gov/docket?D=USCIS-2010-0012)

Proposed Timeline:
- The comment period closes on December 10.
- This proposal is being presented on October 23.
- Goal: to have the database capturing data by the first week in November.

This issue is a continuation of #48 

**Goal**
Set up a database that can be used to store the comments and supporting documents scraped from the regulation.gov page. In the future, we should be able to automatically gather and save new comments and documents.

**Comment by noahbjohnson** [comment]
Could you clarify on where we'd like this to be located. Are we going to create some sort of document store inside of the repository itself, or would looking at a cloud solution be more prudent?

**Comment by dotj** [comment]
@noahbjohnson A cloud solution would probably be more prudent but not completely necessary... though we'll have other data collection projects in the future so it may be worth it! It just needs to be easy to access and share with people that don't have a data background.

**Comment by alejandrox1** [comment]
@dotj can we get specifics on how to store the data? The scraper for comments is more or less ready to go. We need more details to workout how and where the scraper will save data.

**Comment by dotj** [comment]
Thanks for kicking this off, @alejandrox1! Sorry I didn't see this earlier. I am open to recommendations for how to store the data, as is the NILC.

I'll set aside some time to dig into this more tomorrow and hopefully sync with you then. Message me on slack if you have any questions in the meantime.
